---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: dockerhub.thalamus.am/petclinic:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: nexus
